CREATE TABLE IF NOT EXISTS network_proxies (
    id BIGINT NOT NULL AUTO_INCREMENT,
    proxy_url VARCHAR(512) NOT NULL,
    masked_proxy_url VARCHAR(512) NOT NULL,
    protocol VARCHAR(32) NOT NULL DEFAULT 'socks5',
    host VARCHAR(255) NOT NULL,
    port INT NOT NULL,
    username VARCHAR(255) DEFAULT NULL,
    password_encrypted TEXT DEFAULT NULL,
    note VARCHAR(255) DEFAULT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'unknown',
    max_users INT NOT NULL DEFAULT 10,
    success_count INT NOT NULL DEFAULT 0,
    fail_count INT NOT NULL DEFAULT 0,
    avg_latency_ms INT NOT NULL DEFAULT 0,
    last_success_at DATETIME DEFAULT NULL,
    last_fail_at DATETIME DEFAULT NULL,
    cooldown_until DATETIME DEFAULT NULL,
    last_checked_at DATETIME DEFAULT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_network_proxies_proxy_url (proxy_url),
    KEY idx_network_proxies_status (status, updated_at),
    KEY idx_network_proxies_cooldown (cooldown_until)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
